const $=id=>document.getElementById(id);
let mode='pixels',token='',connected=false,pixels=null,active=false,pendingVersion=null,initial=true;
const cells=Array.from({length:36},()=>{const el=document.createElement('div');el.className='pixel';$('grid').append(el);return el});
const names={codex:'Codex 自动联动',pixels:'图片',solid:'纯色',rainbow:'彩虹动画',text:'文字',off:'小屏熄灭',stop:'原厂显示'};
function draw(frame){cells.forEach((el,i)=>{const c=frame?.[i]||[0,0,0];el.style.background=c.some(v=>v)?`rgb(${c.join(',')})`:'#273847'})}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}
function select(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.mode===mode)));['codex','pixels','solid','rainbow','text'].forEach(m=>$(m+'Panel').hidden=m!==mode);$('apply').textContent=mode==='codex'?'开启 / 应用联动':'显示到键盘';preview()}
function preview(){active=false;$('previewLabel').textContent='待发送 · '+names[mode];const b=+$('brightness').value/100;let frame=pixels;if(mode==='solid'){const hex=$('color').value;frame=Array(36).fill([1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)))}if(mode==='rainbow')frame=Array.from({length:36},(_,i)=>{const hue=i/36*6,x=255*(1-Math.abs(hue%2-1));return [[255,x,0],[x,255,0],[0,255,x],[0,x,255],[x,0,255],[255,0,x]][Math.floor(hue)]});if(mode==='text'||mode==='codex')frame=null;draw(frame?.map(c=>c.map(v=>Math.round(v*b))))}
async function poll(){try{const res=await fetch('/api/status');if(!res.ok)throw Error('服务无法连接');const s=await res.json();token=s.token;connected=s.connected;const ai=s.codex;if(ai){$('aiState').textContent=ai.available?ai.label:'未发现本地会话';$('aiEnabled').textContent=s.mode==='codex'?'自动联动中':'未开启联动';$('aiSource').textContent=ai.source?`跟随主对话 …${ai.source} · ${ai.active} 个活跃主任务`:'等待本机 Codex 主任务开始';$('aiDot').style.background=({thinking:'#28bccb',tool:'#9d70df',done:'#36ad78',error:'#e15f61',waiting:'#eda52d',idle:'#94a5b5'})[ai.state]}if(initial){initial=false;$('theme').value=s.theme||'robot';themeHint();$('brightness').value=Math.round((s.brightness??.6)*100);$('brightnessValue').textContent=$('brightness').value+'%';if(s.mode==='codex'){select('codex');active=true;$('previewLabel').textContent='正在显示 · Codex 自动联动';message('自动联动已开启，键盘跟随一轮完整主任务，仅主任务结束时庆祝。')}}$('connection').textContent=connected?`● ${s.transport||'USB'} 键盘已连接`:'● 等待 USB / 2.4G 键盘';$('connection').className=connected?'ok':'bad';$('battery').textContent=s.battery===null?'电量 —':`电量 ${s.battery}%`;if(s.error)message(s.error,true);if(pendingVersion!==null&&s.version>=pendingVersion&&connected){pendingVersion=null;active=s.mode!=='stop';message(s.mode==='stop'?'已停止，屏幕交回键盘原厂控制。':'已发送到键盘。');$('previewLabel').textContent=s.mode==='stop'?'原厂显示（不提供预览）':'正在显示 · '+names[s.mode];if(!active)draw(null)}if(active){draw(s.pixels);if(s.mode==='codex'&&ai)$('previewLabel').textContent='Codex · '+ai.label}}catch(e){connected=false;$('connection').textContent='● 控制服务未启动';$('connection').className='bad';message('请双击「YOGO 小屏」重新启动，再刷新页面。',true)}finally{setTimeout(poll,150)}}
async function send(override){if(!connected)return message('请先通过 USB 或 2.4G 连接键盘，并退出其他键盘控制软件。',true);const chosen=override||mode;if(chosen==='pixels'&&!pixels)return message('请先选择图片，或点击“试试爱心”。',true);const data={theme:$('theme').value,mode:chosen,brightness:+$('brightness').value/100,color:$('color').value,text:$('text').value,pixels};$('apply').disabled=true;try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json','X-Yogo-Token':token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error);pendingVersion=result.version;message('正在发送…')}catch(e){message(e.message,true)}finally{$('apply').disabled=false}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>select(b.dataset.mode));$('brightness').oninput=()=>{$('brightnessValue').textContent=$('brightness').value+'%';preview();message('亮度已调整，点击“显示到键盘”应用。')};$('color').oninput=()=>{$('hex').textContent=$('color').value.toUpperCase();preview()};$('text').oninput=()=>{active=false};$('apply').onclick=()=>send();$('stop').onclick=()=>send('stop');$('off').onclick=()=>send('off');$('heart').onclick=()=>{const pattern=['011110','111111','111111','011110','001100','000000'].join('');pixels=[...pattern].map(v=>v==='1'?[255,50,95]:[0,0,0]);$('filename').textContent='爱心图案已准备好';select('pixels');message('爱心预览已就绪，点击“显示到键盘”。')};$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;if(file.size>15*1024*1024)return message('请选择小于 15 MB 的图片。',true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=6;const ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,6,6);ctx.drawImage(bitmap,0,0,6,6);bitmap.close();const data=ctx.getImageData(0,0,6,6).data;pixels=Array.from({length:36},(_,i)=>Array.from(data.slice(i*4,i*4+3)));$('filename').textContent=file.name;select('pixels');message('图片已准备好，点击“显示到键盘”。')}catch{message('图片无法读取，请选择 PNG、JPG 或 WebP 图片。',true)}};poll();

function themeHint(){ $('themeHint').textContent=({robot:'眨眼待机 · 张望思考 · 踏步工作 · 笑脸与爱心庆祝',garden:'种子待机 · 嫩芽思考 · 雨滴浇灌 · 完成开花',space:'星星待机 · 雷达思考 · 火箭工作 · 完成烟花',simple:'保留原有彗星、呼吸和状态色灯效'})[$('theme').value]; }
$('theme').onchange=()=>{themeHint();if(mode==='codex')send('codex')};
